- src/Components/Menu/Menu.js
- src/Components/Menu/Menu.styles.js
- src/Components/Menu/ModalMenu/index.js
https://media.giphy.com/media/L0CAcHD8nIN8a4QIBv/giphy.gif
> show menu position based on device edge

- docs/src/content/components/badge/Demos/DotDemo.js
- docs/src/content/components/badge/Demos/index.js
- docs/src/content/components/badge/index.js
- src/Components/Badge/Badge.stories.js
This resolves #17 for showing how to create a dot type with  a storybook and doc demo
> add badge dot demo and storybook

- docs/src/content/components/bottom-navigation-item/propData.js
- src/Components/BottomNavigation/BottomNavigation.stories.js
- src/Components/BottomNavigation/BottomNavigation.styles.js
- src/Components/BottomNavigation/BottomNavigationItem/BottomNavigationItem.js
> Clean  up Bottomnavigation demos

- docs/src/content/components/bottom-navigation/Demos/IconsOnly.js
- docs/src/content/components/bottom-navigation/Demos/index.js
- docs/src/content/components/bottom-navigation/index.js
> Add icons only demo to docs

- src/Components/Badge/Badge.stories.js
> 20 add custom section to storybook

- src/Components/Button/Button.stories.js
> 29 add custom button to storybook

- src/Components/Card/Card.js
- src/Components/Card/Card.stories.js
> 34 add more card demos

- src/Components/Checkbox/Checkbox.stories.js
> 40 checkbox stories

- src/Components/DataTable/DataTable.stories.js
> 53 Add datatable row to storybook

- src/Components/DataTable/DataTable.stories.js
> 126 add datatablecell to storybook

- docs/src/content/components/dialog/index.js
- docs/src/content/components/divider/Demos/SubheaderDemo.js
- docs/src/content/components/divider/Demos/index.js
- docs/src/content/components/divider/index.js
- docs/src/content/components/divider/propData.js
- src/Components/Divider/Divider.js
- src/Components/Divider/Divider.stories.js
- src/Components/Divider/Divider.styles.js
- src/Theme/defaultTheme.js
> 60 divider

- docs/src/content/components/icon/MainDemo.js
- src/Components/Icon/Icons.stories.js
> 78 add more icon demos

- docs/src/content/components/iconbutton/MainDemo.js
- docs/src/content/components/iconbutton/propData.js
- src/Components/IconButton/IconButton.js
- src/Components/IconButton/IconButton.stories.js
> 79 add more iconbutton demos

- docs/src/content/utils/hoverable/Demos/AnimatedDemo.js
- docs/src/content/utils/hoverable/Demos/index.js
- docs/src/content/utils/hoverable/index.js
- src/Utils/Hoverable/Hoverable.stories.js
> 109 add animated hover demo

- docs/src/content/components/togglebutton-group/MainDemo.js
- docs/src/content/components/togglebutton-group/Props.js
- docs/src/content/components/togglebutton-group/Usage.js
- docs/src/content/components/togglebutton-group/index.js
- docs/src/content/components/togglebutton-group/propData.js
- docs/src/content/components/togglebutton/Demos/CustomDemo.js
- docs/src/content/components/togglebutton/Demos/index.js
- docs/src/content/components/togglebutton/MainDemo.js
- docs/src/content/components/togglebutton/Usage.js
- docs/src/content/components/togglebutton/index.js
- docs/src/content/components/togglebutton/propData.js
- docs/src/navigation/componentPages.js
- docs/src/pages/components/togglebutton-group.js
- src/Components/ToggleButton/ToggleButton.js
- src/Components/ToggleButton/ToggleButton.stories.js
- src/Components/ToggleButton/ToggleButtonGroup/ToggleButtonGroup.js
> 108 more toggle demos

- docs/src/content/components/ripple/Demos/CenteredDemo.js
- docs/src/content/components/ripple/Demos/SequentialDemo.js
- docs/src/content/components/ripple/Demos/index.js
- docs/src/content/components/ripple/MainDemo.js
- docs/src/content/components/ripple/index.js
- src/Components/Ripple/Ripple.stories.js
> 91 more ripple demos

- docs/src/content/components/radiobutton/Demos/LabelsDemo.js
- docs/src/content/components/radiobutton/Demos/index.js
- docs/src/content/components/radiobutton/MainDemo.js
- docs/src/content/components/radiobutton/index.js
- docs/src/content/components/radiobutton/propData.js
- src/Components/RadioButton/RadioButton.js
- src/Components/RadioButton/RadioButton.stories.js
- src/Components/RadioButton/RadioButton.styles.js
- src/Components/RadioButton/__snapshots__/RadioButton.test.js.snap
> 90 more radio

- docs/src/content/components/appbar/Demos/MenuDemo.js
- docs/src/content/components/menu-item/Demos/IconDemo.js
- docs/src/content/components/menu-item/Demos/KeyboardDemo.js
- docs/src/content/components/menu-item/Demos/index.js
- docs/src/content/components/menu-item/MainDemo.js
- docs/src/content/components/menu-item/Usage.js
- docs/src/content/components/menu-item/index.js
- docs/src/content/components/menu-item/propData.js
- docs/src/content/components/menu/Demos/ScrollingDemo.js
- docs/src/content/components/menu/Demos/index.js
- docs/src/content/components/menu/MainDemo.js
- docs/src/content/components/menu/Usage.js
- docs/src/content/components/menu/index.js
- src/Components/Appbar/Appbar.stories.js
- src/Components/Menu/Menu.js
- src/Components/Menu/Menu.stories.js
- src/Components/Menu/Menu.styles.js
- src/Components/Menu/MenuItem/MenuItem.js
- src/Components/Menu/MenuItem/MenuItem.stories.js
- src/Components/Menu/MenuItem/MenuItem.styles.js
- src/Components/Menu/MenuItem/__snapshots__/MenuItem.test.js.snap
- src/Components/Select/Select.js
- src/storybook/stories/index.js
> 87 menu demos

- docs/src/content/components/appbar-bottom/Demos/SpeedDialDemo.js
- docs/src/content/components/appbar-bottom/Demos/index.js
- docs/src/content/components/appbar-bottom/index.js
- docs/src/content/components/appbar-bottom/propData.js
- docs/src/content/components/fab-speeddial/propData.js
- src/Components/AppbarBottom/AppbarBottom.js
- src/Components/AppbarBottom/AppbarBottom.stories.js
- src/Components/AppbarBottom/AppbarBottom.styles.js
- src/Components/FabSpeedDial/FabSpeedDial.js
- src/Components/FabSpeedDial/FabSpeedDial.styles.js
> 14 appbarbottom speeddial

- docs/src/content/components/switch/Demos/LabelsDemo.js
- docs/src/content/components/switch/Demos/LoaderDemo.js
- docs/src/content/components/switch/Demos/index.js
- docs/src/content/components/switch/MainDemo.js
- docs/src/content/components/switch/index.js
- docs/src/content/components/switch/propData.js
- docs/src/content/components/textfield/propData.js
- src/Components/Checkbox/Checkbox.stories.js
- src/Components/Progress/ProgressCircle/ProgressCircle.js
- src/Components/Switch/Switch.js
- src/Components/Switch/Switch.stories.js
- src/Components/Switch/Switch.styles.js
> 98 switch labels

- docs/src/content/components/badge/Demos/AnimatedDemo.js
- docs/src/content/components/badge/Demos/index.js
- docs/src/content/components/badge/index.js
- docs/src/content/components/badge/propData.js
- src/Components/Badge/Badge.js
- src/Components/Badge/Badge.stories.js
- src/storybook/stories/Home.stories.js
> 19 badge animation

- docs/src/content/components/checkbox/Demos/IOSDemo.js
- docs/src/content/components/checkbox/propData.js
- src/Components/Checkbox/Checkbox.js
- src/Components/Checkbox/Checkbox.stories.js
> 39 add error prop, styles, and demos

- docs/src/content/components/radiobutton/MainDemo.js
- docs/src/content/components/radiobutton/propData.js
- src/Components/RadioButton/RadioButton.js
- src/Components/RadioButton/RadioButton.stories.js
> 149 add radio error state

- docs/src/content/components/dialog/index.js
- docs/src/content/components/fab/Demos/AnimatedDemo.js
- docs/src/content/components/fab/Demos/ExtendedDemo.js
- docs/src/content/components/fab/Demos/MiniDemo.js
- docs/src/content/components/fab/Demos/index.js
- docs/src/content/components/fab/MainDemo.js
- docs/src/content/components/fab/Usage.js
- docs/src/content/components/fab/index.js
- docs/src/content/components/fab/propData.js
- src/Components/Badge/Badge.stories.js
- src/Components/Fab/Fab.js
- src/Components/Fab/Fab.stories.js
closes #72 
closes #73 
closes #74 
closes #75
> 72 fab improvements

- docs/src/content/components/appbar-bottom/Demos/CustomDemo.js
- docs/src/content/components/appbar-bottom/Demos/EndFabDemo.js
- docs/src/content/components/appbar-bottom/Demos/SpeedDialDemo.js
- docs/src/content/components/appbar-bottom/MainDemo.js
- docs/src/content/components/appbar-bottom/Usage.js
- docs/src/content/components/appbar-bottom/propData.js
- src/Components/AppbarBottom/AppbarBottom.js
- src/Components/AppbarBottom/AppbarBottom.stories.js
- src/Components/Fab/Fab.js
> 153 appbar fab

- docs/src/content/components/datatable-cell/Demos/SortingIconDemo.js
- docs/src/content/components/datatable-cell/Demos/index.js
- docs/src/content/components/datatable-cell/index.js
- docs/src/content/components/datatable-cell/propData.js
- docs/src/content/components/datatable-pagination/MainDemo.js
- docs/src/content/components/datatable-pagination/Usage.js
- docs/src/content/components/datatable-pagination/propData.js
- docs/src/content/components/datatable-row/Demos/CheckboxDemo.js
- docs/src/content/components/datatable-row/Demos/SelectedDemo.js
- docs/src/content/components/datatable-row/Demos/index.js
- docs/src/content/components/datatable-row/MainDemo.js
- docs/src/content/components/datatable-row/index.js
- docs/src/content/components/datatable-row/propData.js
- docs/src/content/components/datatable/MainDemo.js
- package.json
- src/Components/DataTable/DataTable.stories.js
- src/Components/DataTable/DataTableCell/DataTableCell.js
- src/Components/DataTable/DataTableCell/DataTableCell.stories.js
- src/Components/DataTable/DataTableCell/DataTableCell.styles.js
- src/Components/DataTable/DataTableHeader/DataTableHeader.stories.js
- src/Components/DataTable/DataTablePagination/DataTablePagination.js
- src/Components/DataTable/DataTablePagination/DataTablePagination.stories.js
- src/Components/DataTable/DataTablePagination/DataTablePagination.styles.js
- src/Components/DataTable/DataTableRow/DataTableRow.js
- src/Components/DataTable/DataTableRow/DataTableRow.stories.js
- src/Components/DataTable/DataTableRow/DataTableRow.styles.js
- src/Components/IconButton/IconButton.js
- src/storybook/stories/index.js
closes #54 
closes #55 
closes #45 
closes #56
closes #46
> 54 fix datatable

- docs/src/pages/contributing/docs.js
> 166 fix sidemenu on contributing to docs

- docs/src/content/components/appbar/Demos/SearchBarDemo.js
> 165 fix searchbar in appbar

- docs/src/content/components/sheet-bottom/MainDemo.js
- docs/src/content/components/sheet-bottom/Props.js
- docs/src/content/components/sheet-bottom/Usage.js
- docs/src/content/components/sheet-bottom/index.js
- docs/src/content/components/sheet-bottom/propData.js
- docs/src/navigation/componentPages.js
- docs/src/pages/components/sheet-bottom.js
- src/Components/List/ListItem/ListItem.js
- src/Components/SheetBottom/SheetBottom.js
- src/Components/SheetBottom/SheetBottom.stories.js
- src/Components/SheetBottom/SheetBottom.styles.js
- src/Components/SheetBottom/SheetBottom.test.js
- src/Components/SheetBottom/__snapshots__/SheetBottom.test.js.snap
- src/index.js
- src/storybook/stories/index.js
> 112 sheet bottom

- docs/src/content/components/sheet-side/MainDemo.js
- docs/src/content/components/sheet-side/Props.js
- docs/src/content/components/sheet-side/Usage.js
- docs/src/content/components/sheet-side/index.js
- docs/src/content/components/sheet-side/propData.js
- docs/src/navigation/componentPages.js
- docs/src/pages/components/sheet-side.js
- src/Components/SheetSide/SheetSide.js
- src/Components/SheetSide/SheetSide.stories.js
- src/Components/SheetSide/SheetSide.styles.js
- src/Components/SheetSide/SheetSide.test.js
- src/Components/SheetSide/__snapshots__/SheetSide.test.js.snap
- src/index.js
- src/storybook/stories/index.js
> 113 sheetside

- .storybook/addons.js
- docs/src/content/components/tooltip/MainDemo.js
- docs/src/content/components/tooltip/Props.js
- docs/src/content/components/tooltip/Usage.js
- docs/src/content/components/tooltip/index.js
- docs/src/content/components/tooltip/propData.js
- docs/src/navigation/componentPages.js
- docs/src/pages/components/tooltip.js
- src/Components/Menu/Menu.js
- src/Components/Menu/ModalMenu/ariaAppHider.js
- src/Components/Menu/ModalMenu/index.native.js
- src/Components/Menu/ModalMenu/index.web.js
- src/Components/Tooltip/Tooltip.js
- src/Components/Tooltip/Tooltip.stories.js
- src/Components/Tooltip/Tooltip.styles.js
- src/Components/Tooltip/Tooltip.test.js
- src/Components/Tooltip/__snapshots__/Tooltip.test.js.snap
- src/Utils/Hoverable/HoverState.js
- src/Utils/Hoverable/Hoverable.js
- src/Utils/Hoverable/__snapshots__/Hoverable.test.js.snap
- src/index.js
- src/storybook/stories/index.js
> 116 tooltip

- docs/src/content/components/drawer-bottom/MainDemo.js
- docs/src/content/components/drawer-bottom/Props.js
- docs/src/content/components/drawer-bottom/Usage.js
- docs/src/content/components/drawer-bottom/index.js
- docs/src/content/components/drawer-bottom/propData.js
- docs/src/navigation/componentPages.js
- docs/src/pages/components/drawer-bottom.js
- src/Components/DrawerBottom/DrawerBottom.js
- src/Components/DrawerBottom/DrawerBottom.stories.js
- src/Components/DrawerBottom/DrawerBottom.test.js
- src/Components/DrawerBottom/__snapshots__/DrawerBottom.test.js.snap
- src/index.js
- src/storybook/stories/index.js
> 62 drawer bottom

- src/Components/Menu/MenuItem/__snapshots__/MenuItem.test.js.snap
- src/Utils/Hoverable/Hoverable.js
- src/Utils/Hoverable/__snapshots__/Hoverable.test.js.snap
Adds a `TouchableWithoutFeedback` around the hoverable component when width is less than `450` or it on a platform that's not the web.
closes #185
> 185 hoverable on touch on mobile

- docs/src/content/components/searchfield/propData.js
- src/Components/TextField/Searchfield/Searchfield.js
Fix for https://github.com/codypearce/material-bread/issues/200
- Added inputRef to SearchField
> Ref for Search TextField

- docs/src/content/components/list-item/propData.js
- src/Components/List/ListItem/ListItem.js
- src/Components/List/ListItem/ListItem.styles.js
Fix for https://github.com/codypearce/material-bread/issues/199
- Added secondaryTextStyle prop to ListItem component
- Removed unnecessary styles from `ListItem.styles.js `
> ListItem secondaryText color

- docs/src/content/components/list-section/propData.js
- src/Components/List/ListSection/ListSection.js
Added a label style for the ListSection and added the prop to the docs.
Fixes: #210
> 210-listsection-label-style

- src/Components/TextField/TextFieldFilled/TextFieldFilled.js
- src/Components/TextField/TextFieldOutline/TextFieldOutline.js
These are generating prop type warnings.
> Update TextField value props to string

- README.md
- docs/src/content/components/swipenav/MainDemo.js
- docs/src/content/components/swipenav/Props.js
- docs/src/content/components/swipenav/Usage.js
- docs/src/content/components/swipenav/index.js
- docs/src/content/components/swipenav/propData.js
- docs/src/navigation/componentPages.js
- docs/src/pages/components/swipenav.js
- ios/MaterialBread.xcodeproj/project.pbxproj
- ios/MaterialBread/AppDelegate.h
- ios/MaterialBread/AppDelegate.m
- ios/MaterialBread/Info.plist
- src/Components/SwipeNav/SwipeNav.js
- src/Components/SwipeNav/SwipeNav.stories.js
- src/Components/SwipeNav/SwipeNav.styles.js
- src/helpers/hasNotch.js
- src/helpers/statusBarHeight.js
- src/index.js
- src/storybook/stories/index.js
Creates SwipeNav Component to close #3
> 3 appbar hide

- src/Components/AppbarBottom/AppbarBottom.stories.js
> 13 sidebar demo

- src/Components/AppbarBottom/AppbarBottom.stories.js
> 10 add drawer bottom demo

- package.json
- src/Components/List/ListItem/ListItem.js
- yarn.lock
In #219 we fixed the animation ending automatically causing onPress to be called.  This was reverted to fix another but.  This is a compromise between the two issues.  Now, on a press, the animation should always end, and the full onPress should actually have to occur.
> ListItem: Add State for onPress

- src/Components/IconButton/IconButton.js
We need this to be able to pass accessibility features into IconButton
> IconButton passes down props

- docs/src/content/components/swipenav/Demos/SwipeFooter.js
- docs/src/content/components/swipenav/Demos/index.js
- docs/src/content/components/swipenav/index.js
- docs/src/content/components/swipenav/propData.js
- src/Components/SwipeNav/SwipeNav.js
- src/Components/SwipeNav/SwipeNav.stories.js
- src/Components/SwipeNav/SwipeNav.styles.js
> 24 hide bottomsheet and appbarbottom

- docs/src/content/components/list-item/propData.js
- src/Components/List/ListItem/ListItem.js
- src/Components/List/ListItem/ListItem.stories.js
I couldn't find a way to customize the `secondaryText` of `ListItem`.
> feat(ListItem): passing element to secondaryText

- src/Components/Card/Card.stories.js
> 35 add card content demo

- docs/src/content/components/card-header/Demos/MoreActions.js
- docs/src/content/components/card-header/Demos/index.js
- docs/src/content/components/card-header/index.js
- src/Components/Card/Card.stories.js
> 36 add another card header demo

- src/Components/Card/Card.stories.js
> 37 create another demo

- src/Components/Drawer/Drawer.test.js
- src/Components/DrawerBottom/DrawerBottom.test.js
- src/Components/TextField/TextFieldFilled/__snapshots__/TextFieldFilled.test.js.snap
- src/Components/TextField/TextFieldFlat/__snapshots__/TextFieldFlat.test.js.snap
- src/Components/TextField/TextFieldLabel/__snapshots__/TextFieldLabel.test.js.snap
**WHY**
Branch master is broken.
> Fix broken tests

- src/Components/DataTable/DataTable.stories.js
> 52 add custom demo for datatable

- src/Components/Banner/Banner.stories.js
> 21 create banner appbar demo

- package.json
> 288 move react-native-svg to peer

- src/Components/Chip/__snapshots__/Chip.test.js.snap
- src/Components/Drawer/DrawerItem/__snapshots__/DrawerItem.test.js.snap
- src/Components/Menu/MenuItem/__snapshots__/MenuItem.test.js.snap
- src/Components/RadioButton/__snapshots__/RadioButton.test.js.snap
- src/Components/Ripple/Ripple.js
> 287 Revert Animated.View for Ripple

- docs/src/content/components/slider/MainDemo.js
- docs/src/content/components/slider/propData.js
- src/Components/Slider/Marker/Marker.js
- src/Components/Slider/Marker/Marker.styles.js
- src/Components/Slider/MarkerContainer/MarkerContainer.js
- src/Components/Slider/MarkerContainer/MarkerContainer.styles.js
- src/Components/Slider/Slider.js
- src/Components/Slider/Track/Track.js
- src/Components/Slider/Track/Track.styles.js
Implemented the proposed solution for issue #295 adding three new props: markerSize, trackHeight, trackStyle.  Also added to the docs properly and provided a demo.
> 295: Slider Customization

- docs/src/content/components/menu/propData.js
- docs/src/content/components/select/propData.js
- src/Components/Menu/Menu.js
- src/Components/Select/Select.js
> 307 add fullwidth prop to select

- src/Components/List/ListSection/ListSection.styles.js
- src/Components/Slider/Slider.js
- src/Components/Slider/Slider.styles.js
- src/Components/Switch/Switch.js
- src/Components/TextField/TextFieldLabel/TextFieldLabel.js
This PR fixes a handful of components that have issues with RTL languages:
- Switch component toggles to the correct direction
- Sliders don't change their layout
- ListSection label aligns itself correctly
- TextFieldLabel fits within the textfield now
> Various RTL fixes

- docs/src/content/components/dialog/propData.js
- src/Components/Dialog/Dialog.js
Added actionItemsContainerStyle prop to Dialog component
> Dialog action buttons style

- src/Components/Drawer/DrawerHeader/DrawerHeader.js
- src/Components/Drawer/DrawerHeader/__snapshots__/DrawerHeader.test.js.snap
Fix missing style props on DrawerHeader component
> Add style props to DrawerHeader component

- docs/src/content/components/slider/propData.js
- src/Components/Slider/Slider.js
- src/Components/Slider/Track/Track.js
This PR adds a prop that allows a dev to change the color of the unselected track on a Slider
> Allow changing of slider track color

- package.json
Adds types entry to packagejson https://github.com/codypearce/material-bread/pull/325#issuecomment-553896993
> Add types entry to packagejson

- src/Components/Progress/ProgressCircle/ProgressCircle.js
This PR adds in the `useNativeDriver` flag to the `ProgressCircle` component. This change improves performance of the animation.
> Add useNativeDriver to progresscircle

- src/Components/List/ListItem/ListItem.js
This PR adds the `alignSelf` style property to the `View` that wraps text and children in a `ListItem`
> ListItem - vertically center children/text

- docs/src/content/components/searchfield/propData.js
- src/Components/TextField/Searchfield/Searchfield.js
> 337 Add separate props for icons and input

- docs/src/content/components/sheet-side/propData.js
- src/Components/SheetSide/SheetSide.android.js
- src/Components/SheetSide/SheetSide.ios.js
- src/Components/SheetSide/SheetSide.web.js
> 344 sheetwidth on web

- docs/src/content/components/appbar/propData.js
- src/Components/Appbar/Appbar.js
- src/Components/Appbar/__snapshots__/Appbar.test.js.snap
> 339 abilty to style appbar actionitems container

- src/Components/Appbar/Appbar.js
- src/Components/SheetSide/SheetSide.web.js
> 341 Fix sheet side staying in the same place while resizing

- docs/src/content/components/drawer-header/Demos/AvatarDemo.js
- docs/src/content/components/drawer-header/MainDemo.js
- docs/src/content/components/drawer-item/MainDemo.js
- docs/src/content/components/drawer-section/Demos/LabelDemo.js
- docs/src/content/components/drawer-section/MainDemo.js
- src/Components/Appbar/Appbar.js
> Fix drawers in the docs showing scrims

- README.md
- docs/src/navigation/gettingStartedPages.js
- docs/src/pages/getting-started/nextjs.js
- docs/src/pages/index.js
- docs/src/styles/global/global.css
Add Nextjs page and update readme
> Add nextjs setup instructions

- docs/src/content/components/button/propData.js
- src/Components/Button/ButtonBase/ButtonBase.js
This PR adds in a prop to the ButtonBase component to allow devs to change the size of the icon within a button
> Add iconSize prop to ButtonBase

- src/Components/Select/Select.js
- src/Components/Select/SelectOutlined/SelectOutlined.stories.js
- yarn.lock
> MB-375 Fix scrolling in Select

- docs/src/content/components/typography/MainDemo.js
- docs/src/content/components/typography/Usage.js
https://fullstacklabs.atlassian.net/browse/MAT-1
> MAT-1 Check and fix Typography docs and styles

- src/Components/Avatar/Avatar.js
https://fullstacklabs.atlassian.net/browse/MAT-7
> MAT-7 change text for typography text

- src/Components/Button/ContainedButton/ContainedButton.js
- src/Components/Button/FlatButton/FlatButton.js
- src/Components/Button/OutlinedButton/OutlinedButton.js
- src/Components/Button/TextButton/TextButton.js
- src/Components/IconButton/IconButton.js
* Create function to change color overlay
* Change hover color overlay
* Change ripple color overlay
MAT-4
> MAT-4 Check and modify buttons overlay

- src/Utils/Shadow/Shadow.stories.js
https://fullstacklabs.atlassian.net/browse/MAT-11
> MAT-11 Add all shadow types to stories

- src/Components/Appbar/Appbar.js
- src/Components/Appbar/Searchbar/Searchbar.styles.js
- src/Components/AppbarBottom/AppbarBottom.styles.js
- src/Components/BottomNavigation/BottomNavigation.styles.js
- src/Components/Button/ContainedButton/ContainedButton.js
- src/Components/Dialog/Dialog.styles.js
- src/Components/Drawer/Drawer.js
- src/Components/Fab/Fab.js
- src/Components/Menu/Menu.styles.js
- src/Components/SheetBottom/SheetBottom.styles.js
- src/Components/SheetSide/SheetSide.styles.js
- src/Components/Switch/Switch.styles.js
https://fullstacklabs.atlassian.net/browse/MAT-2
> MAT-2 Match elevation of components with material ui

- src/Components/Fab/FabSpeedDial/FabSpeedDial.js
https://fullstacklabs.atlassian.net/browse/MAT-22
> MAT-22 Switch icon in FAB speeddial

- src/Components/Fab/FabSpeedDial/FabSpeedDial.stories.js
https://fullstacklabs.atlassian.net/browse/MAT-20
> MAT-20 Fix FAB simple speeddial story

- docs/src/content/components/bottom-navigation-item/propData.js
- docs/src/content/components/bottom-navigation/propData.js
- src/Components/BottomNavigation/BottomNavigation.js
- src/Components/BottomNavigation/BottomNavigation.stories.js
- src/Components/BottomNavigation/BottomNavigationItem/BottomNavigationItem.js
- src/Components/BottomNavigation/BottomNavigationItem/BottomNavigationItem.styles.js
* use showOneLabel to check opacity and label management
* use showAllLabels to show all label+icon items
https://fullstacklabs.atlassian.net/browse/MAT-15
> MAT-15 Add bottom navigation opacity behaviour

- src/Components/AppbarBottom/AppbarBottom.js
- src/Components/AppbarBottom/AppbarBottom.stories.js
https://fullstacklabs.atlassian.net/browse/MAT-13
> MAT-13 Modify fab and appbarBottom styles

- src/Components/Button/Button.stories.js
- src/Components/Button/ContainedButton/ContainedButton.stories.js
- src/Components/Button/FlatButton/FlatButton.stories.js
- src/Components/Button/OutlinedButton/OutlinedButton.stories.js
- src/Components/Button/TextButton/TextButton.stories.js
https://fullstacklabs.atlassian.net/browse/MAT-16
> MAT-16 Create storybook page for right icon buttons

- src/Components/Card/Card.stories.js
- src/Components/Card/CardActions/CardActions.js
- src/Components/Card/CardActions/CardActions.styles.js
- src/Components/Card/CardActions/__snapshots__/CardActions.test.js.snap
- src/Components/Card/CardContent/CardContent.js
- src/Components/Card/CardContent/CardContent.styles.js
- src/Components/Card/CardContent/__snapshots__/CardContent.test.js.snap
- src/Components/Card/CardHeader/CardHeader.js
- src/Components/Card/CardHeader/CardHeader.styles.js
- src/Components/Card/CardHeader/__snapshots__/CardHeader.test.js.snap
- src/Components/Card/CardMedia/CardMedia.js
- src/Components/Card/CardMedia/CardMedia.styles.js
- src/Components/Card/CardMedia/__snapshots__/CardMedia.test.js.snap
- src/Components/IconButton/IconButton.js
https://fullstacklabs.atlassian.net/browse/MAT-26
> MAT-26 Match card component styles

- src/Components/Appbar/__snapshots__/Appbar.test.js.snap
- src/Components/AppbarBottom/__snapshots__/AppbarBottom.test.js.snap
- src/Components/Button/ButtonBase/ButtonBase.js
- src/Components/Button/ContainedButton/ContainedButton.js
- src/Components/Button/FlatButton/FlatButton.js
- src/Components/Button/OutlinedButton/OutlinedButton.js
- src/Components/Button/TextButton/TextButton.js
- src/Components/Drawer/__snapshots__/Drawer.test.js.snap
- src/Components/DrawerBottom/__snapshots__/DrawerBottom.test.js.snap
- src/Components/SheetBottom/__snapshots__/SheetBottom.test.js.snap
- src/Components/SheetSide/__snapshots__/SheetSide.test.js.snap
- src/Components/TextField/TextFieldFilled/__snapshots__/TextFieldFilled.test.js.snap
- src/Components/TextField/TextFieldFlat/__snapshots__/TextFieldFlat.test.js.snap
- src/Components/TextField/TextFieldOutline/__snapshots__/TextFieldOutline.test.js.snap
- src/Theme/defaultTheme.js
Check Contained, Text, Outlined and flat buttons
styles
https://fullstacklabs.atlassian.net/browse/MAT-17
> MAT-17 Modify button styles

- src/Components/DataTable/DataTable.stories.js
- src/Components/DataTable/DataTableCell/DataTableCell.stories.js
- src/Components/DataTable/DataTableRow/DataTableRow.stories.js
https://fullstacklabs.atlassian.net/browse/MAT-29
> MAT-29 Fix datatable row hover storybook

- src/Components/DataTable/DataTableHeader/DataTableHeader.js
- src/Components/DataTable/DataTableHeader/DataTableHeader.styles.js
https://fullstacklabs.atlassian.net/browse/MAT-28
> MAT-28 Modify datatable header styles

- src/Components/DataTable/DataTablePagination/DataTablePagination.js
- src/Components/DataTable/DataTablePagination/DataTablePagination.styles.js
https://fullstacklabs.atlassian.net/browse/MAT-31
> MAT-31 Match designs with footer styles

- src/Components/Button/TextButton/TextButton.stories.js
- src/Components/Card/Card.js
- src/Components/Card/Card.stories.js
- src/Components/Card/CardActions/CardActions.styles.js
- src/Components/Card/CardActions/__snapshots__/CardActions.test.js.snap
https://fullstacklabs.atlassian.net/browse/MAT-25
> MAT-25 Add full card story

- src/Components/Button/TextButton/TextButton.stories.js
- src/Components/Switch/Switch.js
- src/Components/Switch/Switch.stories.js
- src/Components/Switch/Switch.styles.js
https://fullstacklabs.atlassian.net/browse/MAT-48
> MAT-48 Check switch styles

- dist/index.d.ts
- docs/src/content/components/snackbar/MainDemo.js
- docs/src/content/components/snackbar/Usage.js
- docs/src/content/components/snackbar/propData.js
- src/Components/Button/TextButton/TextButton.stories.js
- src/Components/Snackbar/Snackbar.js
- src/Components/Snackbar/Snackbar.stories.js
- src/Components/Snackbar/Snackbar.styles.js
* Modify snackbar styles
* Add no button snackbar story
* change snackbar button for action prop
https://fullstacklabs.atlassian.net/browse/MAT-45
https://fullstacklabs.atlassian.net/browse/MAT-56
> MAT-45 Modify snackbar styles

- src/Components/Button/TextButton/TextButton.stories.js
- src/Components/Menu/Menu.stories.js
- src/Components/Menu/MenuItem/MenuItem.js
- src/Components/Menu/MenuItem/MenuItem.stories.js
- src/Components/Menu/MenuItem/MenuItem.styles.js
- src/Components/Menu/MenuItem/__snapshots__/MenuItem.test.js.snap
https://fullstacklabs.atlassian.net/browse/MAT-38
> MAT-38 Verify menu styles

- src/Components/Card/__snapshots__/Card.test.js.snap
- src/Components/Dialog/Dialog.stories.js
https://fullstacklabs.atlassian.net/browse/MAT-35
> MAT-35 Add and modify dialog stories

- src/Components/List/List.stories.js
- src/Components/List/ListItem/ListItem.js
- src/Components/List/ListItem/ListItem.stories.js
- src/Components/List/ListItem/ListItem.styles.js
https://fullstacklabs.atlassian.net/browse/MAT-37
> MAT-37 Fix list layouts and stories

- src/Components/Card/__snapshots__/Card.test.js.snap
- src/Components/Menu/Menu.stories.js
- src/Components/Menu/MenuItem/MenuItem.stories.js
- src/Components/Menu/MenuItem/MenuItem.styles.js
- src/Components/Menu/MenuItem/__snapshots__/MenuItem.test.js.snap
https://fullstacklabs.atlassian.net/browse/MAT-57
> MAT-57 Fix mobile menu item stories

- src/Components/TextField/TextFieldLabel/TextFieldLabel.js
- With this PR I'm  changing how the TextField label changes to 'Error' when there's an error.
> Remove change label to Error when errors
