codypearce/material-bread

- src/Core/BreadProvider.js
The value prop for the ThemeContext Provider in BreadProvider was not being set.  This meant that the theme set by the user was never used or merged with default.
> Set theme value

- src/Components/Appbar/Searchbar/Searchbar.styles.js
- src/Components/Dialog/Dialog.js
- src/Components/Divider/Divider.js
- src/Components/DrawerBottom/DrawerBottom.js
- src/Components/Fab/Fab.js
- src/Components/Fab/FabSpeedDial/FabSpeedDial.js
- src/Components/List/List.js
- src/Components/List/ListItem/ListItem.js
- src/Components/List/ListSection/ListSection.js
- src/Components/Menu/MenuItem/MenuItem.js
- src/Components/Select/Select.js
- src/Components/Slider/Marker/Marker.js
- src/Components/Snackbar/Snackbar.styles.js
- src/Components/Switch/Switch.js
- src/Components/Switch/Switch.styles.js
- src/Components/Tabs/Tab/Tab.js
- src/Components/TextField/Searchfield/Searchfield.styles.js
- src/Components/Tooltip/Tooltip.js
Fix for #195 
Fixed all Require Cycling warnings being thrown by importing components from their modules instead of from src/index.js.  I'm not sure this is how this should be handled architecturally.  I understand the want to import from a common source, but a user shouldn't have to close 15 warnings to use the library.
@codypearce if you'd like me to address this in a different way let me know.
> Fixed Require Cycling

- docs/src/content/components/progress-circle/index.js
- src/Components/Checkbox/Checkbox.js
- src/Components/Checkbox/Checkbox.styles.js
Fixed the checkbox overflow by adding a flex shrink to the container.  Also fixed an issue in the docs in ProgressCircle.
This fixes #203 and #204
> Fixed overflow & docs issue

- src/Components/Chip/__snapshots__/Chip.test.js.snap
- src/Components/Drawer/DrawerItem/__snapshots__/DrawerItem.test.js.snap
- src/Components/Menu/MenuItem/__snapshots__/MenuItem.test.js.snap
- src/Components/RadioButton/__snapshots__/RadioButton.test.js.snap
- src/Components/Ripple/Ripple.js
- src/Components/Ripple/__snapshots__/Ripple.test.js.snap
The issue here was that without the default prop, not sending in a testID to Ripple would cause Android's JSC to coercing the null into a boolean and then attempt to apply it to a string prop.  This caused Android to red screen error.
Fixes #208
> Set Default for Ripple testID

- .eslintrc
- src/Components/TextField/TextFieldFilled/TextFieldFilled.js
- src/Components/TextField/TextFieldFilled/__snapshots__/TextFieldFilled.test.js.snap
- src/Components/TextField/TextFieldFlat/__snapshots__/TextFieldFlat.test.js.snap
- src/Components/TextField/TextFieldLabel/TextFieldLabel.constants.native.js
- src/Components/TextField/TextFieldLabel/TextFieldLabel.constants.web.js
- src/Components/TextField/TextFieldLabel/TextFieldLabel.js
- src/Components/TextField/TextFieldLabel/TextFieldLabel.styles.js
- src/Components/TextField/TextFieldLabel/__snapshots__/TextFieldLabel.test.js.snap
- src/Components/TextField/TextFieldOutline/TextFieldOutline.js
- src/Components/TextField/TextFieldOutline/TextFieldOutline.styles.js
- src/Components/TextField/TextFieldOutline/__snapshots__/TextFieldOutline.test.js.snap
Fixed: 
- #206 the focused/filled label positioning by basing the size of the text off a font size animation instead of a scale.  The scale was causing us to have to calculate exactly how far each label based on width needed to be translated, but this seems to just work.  Also changed some of the positioning to better fit material, please check me there.
- The label was wrapped in a View such that pointer events can be ignored.  Previously, this was causing taps to be ignored on the label text and focus would not occur.
- The labelStyle passed in from the TextField sub class was not being applied.
> Label positioning fix

- docs/src/content/components/textfield/Demos/LeadingIconDemo.js
- package.json
- src/Components/TextField/TextFieldFilled/TextFieldFilled.js
- src/Components/TextField/TextFieldFlat/TextFieldFlat.js
- src/Components/TextField/TextFieldOutline/TextFieldOutline.js
1. Adds support to render functions in leading icon and trailing icon.
2. Fixes #213 
3. Removed legacy `rnpm` to fix RN60 build warning.
> Add support to functions as icons in TextFields. Removed warnign

- src/Components/TextField/TextFieldFilled/TextFieldFilled.styles.js
- src/Components/TextField/TextFieldFilled/__snapshots__/TextFieldFilled.test.js.snap
Fix for https://github.com/codypearce/material-bread/issues/216
- textAlignVertical only works on Android so is generating a misalignment between iOS and Android
Before: 
After:
> Android - Typed text is a little low

- src/Components/TextField/TextFieldFilled/TextFieldFilled.js
- src/Components/TextField/TextFieldFlat/TextFieldFlat.js
- src/Components/TextField/TextFieldOutline/TextFieldOutline.js
Prevents situations like this from occurring:
After:
> TextFields only render label if it exists

- src/Components/List/ListItem/ListItem.js
Fixes for #224 
[Based on Material Design](https://material.io/design/components/lists.html#specs), the list item's title should be max of 1 line and the subtitle should be max of 2 lines.  This was implemented as well as adding flex-shrink to the container for the children/text.  Without this the flexed row allows the text to overflow.
Before:
After:
> 224 ListItem Truncation

- docs/src/content/components/dialog/propData.js
- src/Components/Dialog/Dialog.js
- src/Components/Dialog/Dialog.stories.js
This PR:
- Adds `titleStyle` prop to allow customizing the Dialog title text
- Adds `supportingTextStyle` prop to allow customizing supporting text
- Adds the ability to put React elements in the `actionItems` prop
- If an object is in `actionItems`, it spreads those values on the `Button` component'
- Updates the docs for Dialog
> Dialog - Customize actionItems, title, and supportingText values

- docs/src/content/components/typography/propData.js
- package.json
- src/Components/Typography/BaseText/BaseTest.test.js
- src/Components/Typography/BaseText/BaseText.js
- src/Components/Typography/BaseText/__snapshots__/BaseTest.test.js.snap
- src/Components/Typography/Typography.stories.js
This PR addresses issue #234 by updating the `BaseText` component to have a `themeColor` prop in order to both respect the primary color as defined in the `textColor` theme property, as well as more easily change that color to secondary, hint, disabled, etc.
> 234 - base text theme

- .storybook/config.js
- docs/src/content/components/icon/Demos/AnotherSourceDemo.js
- docs/src/content/components/icon/Demos/index.js
- docs/src/content/components/icon/MainDemo.js
- docs/src/content/components/icon/index.js
- docs/src/content/components/icon/propData.js
- docs/src/content/components/iconbutton/Demos/AnotherSourceDemo.js
- docs/src/content/components/iconbutton/Demos/index.js
- docs/src/content/components/iconbutton/MainDemo.js
- docs/src/content/components/iconbutton/index.js
- docs/src/content/components/iconbutton/propData.js
- docs/src/styles/global/global.css
- src/Components/Icon/Icon.js
- src/Components/Icon/Icons.stories.js
- src/Components/IconButton/IconButton.js
- src/Components/IconButton/IconButton.stories.js
Added an iconComponet prop to Icon and IconButton to allow the user to pass in an icon component and falling back to MaterialIcons.
Fix for #239
> 239-support-icon-sources

- src/Components/Button/ContainedButton/ContainedButton.js
- src/Components/Button/FlatButton/FlatButton.js
- src/Components/Button/OutlinedButton/OutlinedButton.js
- src/Components/Button/TextButton/TextButton.js
- src/Utils/Hoverable/Hoverable.js
The containerStyle prop is listed in the docs, but wasn't actually being used anywhere in most cases.
I was trying to use `width: '100%'` for the buttons inside a flex container with `alignItems: 'center'`, but it wasn't working because the style wasn't being applied to the button containers.
> Button components use containerStyle

- docs/src/content/components/list-item/propData.js
- src/Components/List/ListItem/ListItem.js
This PR adds in `textProps` and `secondaryTextProps` to the `ListItem` component. The change allows for more customization of how the text is rendered inside of a ListItem, such as changing `numberOfLines` from `1` to `2`.
> Add text props to ListItem

- src/Components/Dialog/Dialog.js
- src/Components/Dialog/Dialog.styles.js
The Dialog component wasn't displaying its actions on web because the scroll was invisible, whereas on mobile it shows the scroll but the actions are invisible.
Before:
Fixed
Before:
Fixed:
> fix: dialog

- docs/src/content/components/divider/Demos/InsetLeftDemo.js
- docs/src/content/components/divider/Demos/SubheaderDemo.js
- docs/src/content/components/divider/Demos/index.js
- docs/src/content/components/divider/index.js
- docs/src/content/components/divider/propData.js
- src/Components/Divider/Divider.js
- src/Components/Divider/Divider.stories.js
- src/Components/Divider/__snapshots__/Divider.test.js.snap
- src/Components/Icon/Icon.js
* `inset` has been renamed to `insetHeader` to better indicate what the inset applies too
* `insetLeft` has been added to `<Divider />` this shortens the divider by a specific amount and pushes it over that same amount to create inset dividers shown in the [Material Docs]( https://material.io/components/dividers/#types).
Closes #61
> 61 divider inset

- docs/src/content/components/searchfield/propData.js
- src/Components/TextField/Searchfield/Searchfield.js
In order to properly use the search field the TextInput needs to be addressable with props.  In other places in the library, we've used the rest props for this.  I've included the rest props and added the to the TextInput.
> Spread input props on Searchfield

- docs/src/content/components/checkbox/propData.js
- src/Components/Checkbox/Checkbox.js
- src/Components/Checkbox/Checkbox.styles.js
Added a size prop that scales the ripple, default icons, and default custom icon size.  The default for this prop remains its original value of 24 and the proportions for the ripple's `padding` and `rippleContainerBorderRadius` have been maintained.
> Scalable Checkbox Sizing

- src/Components/Appbar/Appbar.js
With the following code:
`
<Appbar title='Test' elevation={1} />
`
iOS before:
iOS after:
Android before:
Android after:
> Fix Appbar's elevation

- docs/src/content/components/button/propData.js
- src/Components/Button/ButtonBase/ButtonBase.js
By default in Material, buttons should be capitalized, but this gives the user the option to use input casing in case their designs have text in a button that is not capitalized.  Children could also be used here, but this solution uses MB's own rendering to accomplish it which seems easier to use and more consistent than children.
> Added prop to use input casing for buttons

- src/Components/Fab/FabSpeedDial/FabSpeedDial.js
This PR enable user to use onPress function on fabdial element. in order to use like a single fab button. This is useful to avoid replace fabdial with fab button in cases where you only need a single element.
> SpedDial with only one fab button is now able to execute onPress function.

- src/Components/SheetBottom/SheetBottom.web.js
On short screens, the sheetbottom sometimes does not apper, it should be fixed to the bottom.
> Fix the sheetbottom to the bottom of the page on web

- src/Components/Drawer/Drawer.js
I had a situation when using the drawer with react navigation where the safe area view was causing problems. This solved my problem, but let me know if there's a way to go about this, though I'd rather not try to disable safe views in react-navigation, and we have some screens that need to be full screen.
thanks @codypearce !! 🍞 🍻 
#365
> Make needs safe area a prop that defaults to true on iOS

- src/Components/TextField/TextFieldFilled/TextFieldFilled.js
I was getting a yellow box when using the TextFieldFilled component (see #364). it looks like this is how value is being passed by the other TextField components and a quick check shows `''` evals to falsy the way it's being used in TextFieldLabel, so no need for the length check, I think.
> Make filled text field send value prop type consistent with other TextField components

- src/Components/Tabs/Tab/Tab.js
- src/Components/Tabs/Tabs.js
- src/Components/Tabs/Underline/Underline.js
This PR adds in a `containerStyle` prop to the `Tab` component to be able to override the default styles applied. I've also fixed a handful of yellowboxes I discovered while using `Tabs` and `Tab`
> Add `containerStyle` prop to `Tab`, fix various yellowboxes

- src/Components/TextField/TextFieldLabel/TextFieldLabel.js
This PR fixes an issue where the position of a `TextFieldLabel` wouldn't update if the value of the TextField changed
> Fix label not updating if value changes

- src/Components/Tabs/Tabs.js
This PR fixes an issue where the Tabs component would render incorrectly when a device is set to RTL mode
> Fix selected tab working with RTL
